export const GET_STOCKS_REQUEST_ASYNC = 'GET_STOCKS_REQUEST_ASYNC'
export const GET_STOCKS_REQUEST = 'GET_STOCKS_REQUEST'
export const GET_STOCKS_SUCCESS = 'GET_STOCKS_SUCCESS'
export const GET_STOCKS_FAILURE = 'GET_STOCKS_FAILURE'

export const GET_STOCK_DETAIL_REQUEST_ASYNC = 'GET_STOCK_DETAIL_REQUEST_ASYNC'
export const GET_STOCK_DETAIL_REQUEST = 'GET_STOCK_DETAIL_REQUEST'
export const GET_STOCK_DETAIL_SUCCESS = 'GET_STOCK_DETAIL_SUCCESS'
export const GET_STOCK_DETAIL_FAILURE = 'GET_STOCK_DETAIL_FAILURE'
